# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: "en_core_web_md"

pipeline:
# this is using the spacy sklearn pipeline, adding duckling
# all components will use their default values- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_entity_featurizer_regex"
- name: "intent_featurizer_spacy"
- name: "ner_spacy"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "intent_classifier_sklearn"

policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: MappingPolicy
